/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.overpass;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.Arrays;

import de.appwerft.krollplus.*;

import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiC;
import org.appcelerator.titanium.TiProperties;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import com.loopj.android.http.AsyncHttpClient;
import com.loopj.android.http.JsonHttpResponseHandler;
import com.loopj.android.http.RequestParams;

import cz.msebera.android.httpclient.Header;

@Kroll.module(name = "Overpass", id = "de.appwerft.overpass")
public class OverpassModule extends KrollModule {

	private final class OverpassResponseHandler extends JsonHttpResponseHandler {
		@Override
		public void onFailure(int statusCode, Header[] headers,
				Throwable throwable, JSONObject errorResponse) {
		}

		@Override
		public void onFailure(int statusCode, Header[] headers,
				Throwable throwable, JSONArray errorResponse) {
		}

		@Override
		public void onFailure(int statusCode, Header[] headers,
				String responseString, Throwable throwable) {
			if (onResult != null) {
				Log.d(LCAT, "status=" + statusCode);
				KrollDict dict = new KrollDict();
				dict.put("status", statusCode);
				if (System.currentTimeMillis() - startTime < 100) {
					dict.put("error", "offline");
					dict.put("message", "Host not reachable");
				} else {
					dict.put("error", "timeout");
					dict.put("time", ""
							+ (System.currentTimeMillis() - startTime));
					dict.put("message", "Server don't answer in 30 sec. ");
				}
				onResult.call(getKrollObject(), dict);
			}
		}

		@Override
		public void onSuccess(int statusCode, Header[] headers,
				JSONObject response) {

			if (onResult != null) {
				KrollDict res = new KrollDict();
				res.put("success", true);
				try {
					res.put("result", new KrollDict(response));
				} catch (JSONException e) {
					e.printStackTrace();
				}
				onResult.call(getKrollObject(), res);
			}
		}
	}

	private static final String LCAT = "Openpass";
	@Kroll.constant
	public static final String ENDPOINT_MAIN = "http://overpass-api.de/api/";
	@Kroll.constant
	public static final String ENDPOINT_RAMBLER = "http://overpass.osm.rambler.ru/cgi/";
	@Kroll.constant
	public static final String ENDPOINT_FRENCH = "http://api.openstreetmap.fr/oapi/interpreter/";
	private String ENDPOINT = ENDPOINT_FRENCH;
	private int TIMEOUT = 30000;

	private KrollFunction onResult;
	private long startTime;

	public OverpassModule() {
		super();
		TiProperties appProperties = TiApplication.getInstance()
				.getAppProperties();
		ENDPOINT = appProperties.getString("OVERPASS_ENDPOINT", "");
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {

		Log.d(LCAT, "inside onAppCreate");
	}

	@Kroll.method
	public void createRequest(String query, Object res)
			throws UnsupportedEncodingException {
		if (res != null & res instanceof KrollFunction)
			onResult = (KrollFunction) res;
		doQuery(query);
	}

	@Kroll.method
	public void getStreetsByPosition(KrollDict options, Object res)
			throws UnsupportedEncodingException {
		if (res != null & res instanceof KrollFunction)
			onResult = (KrollFunction) res;
		double radius = 1000.0;
		if (options.containsKeyAndNotNull(TiC.PROPERTY_LATITUDE)) {
			double lat = options.getDouble(TiC.PROPERTY_LATITUDE);
			if (options.containsKeyAndNotNull(TiC.PROPERTY_LONGITUDE)) {
				double lon = options.getDouble(TiC.PROPERTY_LONGITUDE);
				if (options.containsKeyAndNotNull("radius")) {
					radius = options.getDouble("radius");
				}
				String query = "way[highway][name](around:" + radius + ","
						+ lat + "," + lon + ");(._;>;)";
				doQuery(query);
			}
		}

	}

	@Kroll.method
	public void getPOIs(KrollDict options, Object res)
			throws UnsupportedEncodingException {
		if (res != null & res instanceof KrollFunction)
			onResult = (KrollFunction) res;
		for (String key : options.keySet()) {
			if (key.equals("bbx")) {
				Float[] coords = toFloatArray(options.get("bbx"));
			} else {

			}
		}

	}

	private Float[] toFloatArray(Object objectArray) {
		if (!(objectArray.getClass().isArray())) {
			throw new IllegalArgumentException("bbx must be an array");
		}

		Object[] coordsArray = (Object[]) objectArray;
		Float[] floatArray = Arrays.copyOf(coordsArray, coordsArray.length,
				Float[].class);
		/*
		 * float[] coords = new float[coordsArray.length];
		 * 
		 * for (int i = 0; i < coordsArray.length; i++) { coords[i] = ((Number)
		 * coordsArray[i]).floatValue(); }
		 */
		return floatArray;
	}

	private void doQuery(String query) throws UnsupportedEncodingException {
		AsyncHttpClient client = new AsyncHttpClient();
		client.setTimeout(TIMEOUT);
		startTime = System.currentTimeMillis();
		String url = ENDPOINT + "?data=[out:json];"
				+ URLEncoder.encode(query + "out body;", "UTF-8");
		RequestParams params = null;
		client.get(url, params, new OverpassResponseHandler());

	};

	@Kroll.setProperty
	public void setEndpoint(String ep) {
		this.ENDPOINT = ep;
	}

}
